name: Deploy FastAPI Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 30m
          script: |
            set -e

            cd ~/Astroma-backend

            echo "Fetching latest code..."
            git fetch origin main
            git reset --hard origin/main

            echo "Enabling BuildKit..."
            export DOCKER_BUILDKIT=1

            echo "Building image..."
            docker-compose build

            echo "Starting updated containers..."
            docker-compose up -d

            echo "Cleaning unused images..."
            docker image prune -f

            echo "Deployment completed successfully"